# Generated by Django 2.1.7 on 2019-05-02 14:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('mailbox', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('profiles', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='签名')),
                ('is_Delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Userbalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.PositiveIntegerField(default=0, verbose_name='余额')),
                ('coin', models.PositiveIntegerField(default=0, verbose_name='硬币')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userspace.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户余额',
                'verbose_name_plural': '用户余额',
                'db_table': 'userbalance',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Usergrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.PositiveIntegerField(default=0, verbose_name='等级')),
                ('readtime', models.PositiveIntegerField(default=0, verbose_name='阅读时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userspace.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户等级',
                'verbose_name_plural': '用户等级',
                'db_table': 'usergrade',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Userhistroy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True, verbose_name='状态更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Book', verbose_name='图书')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Subsection', verbose_name='分卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userspace.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户历史',
                'verbose_name_plural': '用户历史',
                'db_table': 'userhistroy',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
