# Generated by Django 2.1.7 on 2019-05-02 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
        ('userspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collectiontime', models.DateTimeField(blank=True, null=True, verbose_name='收藏时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userspace.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'usercollection',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Usermessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='消息内容')),
                ('collectiontime', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_message', to='userspace.User', verbose_name='消息发送者')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_message', to='userspace.User', verbose_name='消息接受者')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
                'db_table': 'usermessage',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
