# Generated by Django 2.1.7 on 2019-05-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0002_usercollection_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='用户名'),
        ),
    ]
