# Generated by Django 2.1.7 on 2019-05-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0003_auto_20190502_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='collectiontime',
            new_name='messagetime',
        ),
    ]
