# Generated by Django 2.1.7 on 2019-05-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0004_auto_20190502_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_Delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='is_views',
            field=models.BooleanField(default=False, verbose_name='是否查看'),
        ),
    ]
