# Generated by Django 2.1.7 on 2019-05-30 09:01

from django.db import migrations, models
import userspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0006_usercollection_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='expirationdate',
            field=models.DateTimeField(default=userspace.models.settime_asvip, verbose_name='vip过期时间'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否是vip'),
        ),
        migrations.AddField(
            model_name='usergrade',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='经验值'),
        ),
    ]
