# Generated by Django 2.1.7 on 2019-06-06 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0007_auto_20190530_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userreadtime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sumtime', models.IntegerField(verbose_name='本月的阅读时间')),
                ('lasttime', models.IntegerField(verbose_name='状态最后更新时间戳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userspace.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户每月的阅读时间统计',
                'verbose_name_plural': '用户每月的阅读时间统计',
                'db_table': 'userreadtime',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
